name: Publish image to Docker hub

on:
  [workflow_dispatch]

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        run: |
          docker build . -t artyomnortal/provider-adapter-python:latest
      - name: publish
        run: |
          docker login -u artyomnortal -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push artyomnortal/provider-adapter-python:latest
