name: Docker image CI for GHCR

on:
  push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: artyomdevnow/${{ github.event.repository.name }} # <account>/<repo>

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PH_TOKEN }}

      - name: Build and push container
        env:
          IMAGE_TAG: ghcr.io/${{ IMAGE_NAME }}:latest
        run: |
          docker-compose build
          docker-compose push
          docker tag <your_image_name> $IMAGE_TAG
          docker push $IMAGE_TAG